language: node_js

services:
  - mysql

cache:
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email: false

node_js:
  - '8'

before_install:
  - npm i -g npm@^5.5.1
  - npm i -g lerna@^2.5.1

script:
  - lerna bootstrap
  - lerna run create-db
  - lerna run build
  - lerna run test

after_success:
